sudo: required
language: python
dist: bionic
matrix:
  include:
    # https://docs.python.org/devguide/#status-of-python-branches
    # One build pulls latest versions dynamically
    - python: 3.9
      env: CDH=cdh6 CDH_VERSION=6.3.4 PRESTO=0.275 TRINO=393 SQLALCHEMY=sqlalchemy>=1.4.0
    # - python: 3.6
    #   env: CDH=cdh6 CDH_VERSION=6.3.4 PRESTO=0.275 TRINO=393 SQLALCHEMY=sqlalchemy>=1.4.0
    # - python: 3.5
    #   env: CDH=cdh6 CDH_VERSION=6.3.4 PRESTO=0.275 TRINO=393 SQLALCHEMY=sqlalchemy>=1.4.0
    # - python: 3.4
    #   env: CDH=cdh6 CDH_VERSION=6.3.4 PRESTO=0.275 TRINO=393 SQLALCHEMY=sqlalchemy>=1.4.0
    # - python: 2.7
    #   env: CDH=cdh6 CDH_VERSION=6.3.4 PRESTO=0.275 TRINO=393 SQLALCHEMY=sqlalchemy>=1.4.0
install:
  - ./scripts/travis-install.sh
  - pip install codecov
script: PYTHONHASHSEED=random pytest -v
after_success: codecov
